routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/parser', 'ParserController@index');
Route::get('/error', 'AppController@error');
Route::get('/sitemap', 'SitemapController@index');
Route::get('/{path?}', 'AppController@index')
    ->middleware('guest')
    ->where(['path' => '[0-9a-zA-Z\\-_/]*'])
    ->name('app');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Item extends Model
{
    const IMAGE_PATH = '/uploads/items/';
    
    /**
     * @var string
     */
    protected $table = 'items';

    protected $itemSeasonClass = ItemSeason::class;
    protected $userWatchesClass = UserWatch::class;
    protected $listsClass = Lists::class;
    protected $itemVideosClass = ItemVideo::class;
    protected $userRatingClass = UserRating::class;
    protected $userItemsClass = UserItem::class;

    /**
     * @var array
     */
    protected $fillable = [
        'category_id',
        'name_ru',
        'name_en',
        'name_original',
        'description',
        'image',
        'season_count',
        'series_count',
        'rating',
        'rating_kp',
        'rating_imdb',
        'started_at',
        'completed_at',
        'year_start',
        'year_complete',
        'kinopoisk_id',
        'published',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'category_id' => 'integer',
        'name_ru' => 'string',
        'name_en' => 'string',
        'name_original' => 'string',
        'description' => 'string',
        'image' => 'string',
        'year_start' => 'integer',
        'year_complete' => 'integer',
        'season_count' => 'integer',
        'series_count' => 'integer',
        'rating' => 'float',
        'rating_kp' => 'float',
        'rating_imdb' => 'float',
        'attrs' => 'array',
        'video_types' => 'array',
        'kinopoisk_id' => 'integer',
        'published' => 'boolean',
    ];

    /**
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'started_at',
        'completed_at',
    ];

    protected $aggregateAttrIds = [1, 2, 3];

    public function attrValues()
    {
        return $this->belongsToMany(AttrValue::class, 'item_attrs', 'item_id', 'attr_value_id')
            ->orderBy('sort')
            ->with('attr');
    }

    public function seasons()
    {
        return $this->hasMany($this->itemSeasonClass, 'item_id', 'id')
            ->orderBy('number')
            ->with('series');
    }

    public function userItems()
    {
        return $this->hasMany($this->userItemsClass, 'item_id', 'id')
            ->where('user_id', Auth::check() ? Auth::id() : 0);
    }
    
    public function userLists()
    {
        return $this->belongsToMany($this->listsClass, 'user_items', 'item_id', 'list_id')
            ->withPivot('season_number', 'series_number')
            ->whereRaw('(user_items.user_id IS NULL OR user_items.user_id = '.(Auth::check() ? Auth::user()->id : 0).')')
            ->orderBy('sort');
    }

    public function userWatches()
    {
        return $this->hasMany($this->userWatchesClass, 'item_id', 'id')
            ->where('user_id', (Auth::check() ? Auth::user()->id : 0));
    }

    public function videos()
    {
        return $this->hasMany($this->itemVideosClass, 'item_id', 'id');
    }
    
    public function userRating()
    {
        return $this->belongsTo($this->userRatingClass, 'id', 'item_id')
            ->where('user_id', (Auth::check() ? Auth::user()->id : 0));
    }

    public function userRatings()
    {
        return $this->hasMany($this->userRatingClass, 'item_id', 'id');
    }

    public function getImageSrcAttribute($value)
    {
        return $this->image ?
            url(self::IMAGE_PATH . $this->image) :
            url('/images/item_no_image.png');
    }

    /**
     * @return $this
     */
    public function updateAttrs()
    {
        $attrs = [];
        foreach ($this->attrValues as $itemAttr) {
            if (!in_array($itemAttr->attr_id, $this->aggregateAttrIds)) {
                continue;
            }
            if (!isset($attrs[$itemAttr->attr->slug])) {
                $attrs[$itemAttr->attr->slug] = [
                    'id' => $itemAttr->attr->id,
                    'name' => $itemAttr->attr->name,
                    'sort' => $itemAttr->attr->sort,
                    'values' => [],
                ];
            }
            $attrs[$itemAttr->attr->slug]['values'][$itemAttr->id] = array_only($itemAttr->toArray(), ['id', 'value', 'sort']);
        }

        uasort($attrs, function ($a, $b) {
            return $a['sort'] <=> $b['sort'];
        });
        $this->attrs = $attrs;

        return $this;
    }
    
    public function syncAggregate()
    {
        $seasonCount = 0;
        $seriesCount = 0;
        foreach ($this->seasons as $season) {
            $seasonCount++;
            $seriesCount += count($season->series);
        }
        $this->season_count = $seasonCount;
        $this->series_count = $seriesCount;

        return $this;
    }

    public function videoTypesAggregate()
    {
        $videoTypes = null;
        $videoTypesIds = $this->videos()->select('video_type_id')->distinct()->get()->pluck('video_type_id');
        if (!empty($videoTypesIds)) {
            $videoTypes = [];
            foreach (VideoType::whereIn('id', $videoTypesIds)->orderBy('id')->get() as $videoType) {
                $videoTypes[$videoType->id] = [
                    'id' => $videoType->id,
                    'name' => $videoType->name,
                ];
            }
        }
        $this->published = (bool)$videoTypes;
        $this->video_types = $videoTypes;
        return $this;
    }

    public function calculateRating()
    {
        $result = $this->userRatings()
            ->select(DB::raw('count(*) as rating_count, sum(value) as rating_sum'))
            ->first();
        if ($result->rating_count && $result->rating_sum) {
            $this->rating = $result->rating_sum / $result->rating_count;
        } else {
            $this->rating = null;
        }
        return $this->save();
    }

    public function uploadPath(string &$fileName): string
    {
        $fileName = substr($fileName, 0, 2)
            . '/'
            . substr($fileName, 2, 2)
            . '/'
            . $fileName;

        return public_path('uploads/items/' . $fileName);
    }

    public function getNameAttribute(): ?string
    {
        return $this->name_ru ?? $this->name_en ?? $this->name_original;
    }

    public function getUrlAttribute(): string
    {
        return url("/item/{$this->id}");
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>{{ $seoTitle or '' }}</title>
    <meta name="description" content="{{ $seoDescription or '' }}">
    <meta name="keywords" content="{{ $seoKeywords or '' }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="application-name" content="Телесериальчик">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#55AEFF">
    <meta name="apple-mobile-web-app-title" content="Телесериальчик">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <link rel="manifest" href="{{ asset('manifest.json') }}">
    @if ($isMobileVersion)
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/css/mobile-app.css?v6">
    @else
        <meta name="viewport" content="width=1240">
        <link rel="stylesheet" type="text/css" href="/css/app.css?v4">
    @endif

    @if ($item)
        <meta property="og:url" content="{!! $request->url() !!}" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Смотреть сериал «{{ $item->name }}» все серии онлайн" />
        <meta property="og:description" content="{{ $item->description }}" />
        @if ($item->image)
            <meta property="og:image" content="{!! $item->image_src !!}" />
        @endif
    @endif
</head>
<body>
    @if (env('APP_ENV') === 'production')
        <script src="https://cdn.ravenjs.com/3.24.0/raven.min.js" crossorigin=anonymous></script>
        <script>
            Raven.config('{{ env('SENTRY_LARAVEL_DSN') }}', {
                release: '0-0-0',
                environment: 'development-test',
            }).install();
        </script>
    @endif

    <div id="root">
        <script type="text/javascript">
            window.authUser = {!! Auth::check() ? json_encode(Auth::user()->toArray()) : 'null' !!};
            window.lists = {!! $listsJson !!};
            window.isMobileVersion = {!! $isMobileVersion ? 'true' : 'false' !!};
        </script>
    </div>
    <div id="vk_api_transport"></div>

    @if (env('APP_ENV') === 'production')
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter49598884 = new Ya.Metrika2({
                            id:49598884,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true,
                            webvisor:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/tag.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks2");
        </script>
        {{--<noscript><div><img src="https://mc.yandex.ru/watch/49598884" style="position:absolute; left:-9999px;" alt="" /></div></noscript>--}}
        <!-- /Yandex.Metrika counter -->
    @endif

    <script type="text/javascript" src="/js/app.js?v6"></script>
</body>
</html>